name: ci
on:
  push:
    branches:
      - "master"
    tags:
      - '*.*.*'
jobs:
  CI:
    runs-on: ubuntu-latest
    name: devsecops-laboratory
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified