name: ci
on:
  push:
    branches:
      - "master"
    tags:
      - '*.*.*'
jobs:
  CI:
    runs-on: ubuntu-latest
    name: devsecops-laboratory
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run TruffleHog
        run: |
          docker pull dxa4481/trufflehog
          ls ${{ github.workspace }}
          docker run -v ${{ github.workspace }}:/target dxa4481/trufflehog file:///target
      - name: Run Talisman
        run: |
          set -e
          sh -c "git config --global --add safe.directory $PWD"
          sh -c "echo $* | talisman --githook pre-push"