name: ci
on:
  push:
    branches:
      - "master"
    tags:
      - '*.*.*'
jobs:
  CI:
    runs-on: ubuntu-latest
    name: devsecops-laboratory
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run TruffleHog
        run: |
          docker pull dxa4481/trufflehog
          docker run -v ${{ github.workspace }}:/target dxa4481/trufflehog file:///target